name: Deploy sha256-web to GitHub Pages

on:
  push:
    branches: [main] # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload sha256-web
        uses: actions/upload-pages-artifact@v3
        with:
          path: sha256-web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
